//! `fitFDist` / `fitFDistRobustly` against the `scalar/fitfdist_*` goldens: the scalar
//! outputs in `*_scalars.json` and the per-gene vectors in `*_vectors.csv`, generated by
//! `fitFDist(s2, df1)`, `fitFDistRobustly(s2, df1)`, `fitFDist(s2, df1, covariate = amean)`
//! and `fitFDistRobustly(s2, df1, covariate = amean)`. Prior df and scale are held at the
//! manifest's `df_prior`/`s2_prior` tolerance of rel 1e-6.

mod common;

use common::{scalar_dir, Report, Table, Tol};
use limma_core::ebayes::{fit_f_dist, fit_f_dist_robustly};
use serde::Deserialize;

const REL_1E6: Tol = Tol {
    rel: 1e-6,
    abs_floor: 0.0,
};
const CASES: [&str; 3] = ["n200_df4", "n2000_df10", "n5000_df3"];

#[derive(Deserialize)]
struct Plain {
    scale: f64,
    df2: f64,
}
#[derive(Deserialize)]
struct Df2Only {
    df2: f64,
}
#[derive(Deserialize)]
struct Scalars {
    n: usize,
    df1: f64,
    plain: Plain,
    robust: Plain,
    trend: Df2Only,
    robtrend: Df2Only,
}

#[test]
fn fitfdist_matches_golden() {
    let Some(dir) = scalar_dir("fitfdist_matches_golden") else {
        return;
    };
    for case in CASES {
        let json = std::fs::read_to_string(dir.join(format!("fitfdist_{case}_scalars.json")))
            .expect("scalars.json");
        let want: Scalars = serde_json::from_str(&json).expect("parse scalars.json");
        let vectors = Table::read(&dir, &format!("fitfdist_{case}_vectors.csv"));
        assert_eq!(vectors.rows.len(), want.n);
        let col = |name: &str| -> Vec<f64> { vectors.rows().map(|r| r.get(name)).collect() };
        let s2 = col("s2");
        let df1 = col("df1");
        assert!(df1.iter().all(|&d| d == want.df1));
        let amean = col("amean");
        let mut report = Report::new(&format!("fitfdist_{case}"));

        let plain = fit_f_dist(&s2, &[want.df1], None).expect("fitFDist");
        report.check(REL_1E6, "plain.scale", plain.scale[0], want.plain.scale);
        report.check(REL_1E6, "plain.df2", plain.df2, want.plain.df2);

        let robust =
            fit_f_dist_robustly(&s2, &[want.df1], None, [0.05, 0.1]).expect("fitFDistRobustly");
        report.check(REL_1E6, "robust.scale", robust.scale[0], want.robust.scale);
        report.check(REL_1E6, "robust.df2", robust.df2, want.robust.df2);
        let shrunk = col("robust_df2_shrunk");
        for (i, (&g, &w)) in robust.df2_shrunk.iter().zip(&shrunk).enumerate() {
            report.check(REL_1E6, format!("robust.df2.shrunk[{}]", i + 1), g, w);
        }

        let trend = fit_f_dist(&s2, &[want.df1], Some(&amean)).expect("fitFDist trend");
        report.check(REL_1E6, "trend.df2", trend.df2, want.trend.df2);
        let scale = col("trend_scale");
        for (i, (&g, &w)) in trend.scale.iter().zip(&scale).enumerate() {
            report.check(REL_1E6, format!("trend.scale[{}]", i + 1), g, w);
        }

        let robtrend = fit_f_dist_robustly(&s2, &[want.df1], Some(&amean), [0.05, 0.1])
            .expect("fitFDistRobustly trend");
        report.check(REL_1E6, "robtrend.df2", robtrend.df2, want.robtrend.df2);
        let scale = col("robtrend_scale");
        for (i, (&g, &w)) in robtrend.scale.iter().zip(&scale).enumerate() {
            report.check(REL_1E6, format!("robtrend.scale[{}]", i + 1), g, w);
        }
        let shrunk = col("robtrend_df2_shrunk");
        for (i, (&g, &w)) in robtrend.df2_shrunk.iter().zip(&shrunk).enumerate() {
            report.check(REL_1E6, format!("robtrend.df2.shrunk[{}]", i + 1), g, w);
        }
        report.finish();
    }
}
